### PR TITLE
adds login + logout button that hides certain content

### PR DESCRIPTION
**Pull request by chiazo**
this is what it currently looks like; when you click login, it will reveal the form and the logout button while hiding the login button. I'm going to add materializecss to the project and make the buttons look nicer!

Screen Shot 2020-07-05 at 3 00 52 PM

### CODE REVIEW

**Comment by deeptivaidy** [comment]
Awesome! It looks like you added some of your target files as well, could you remove those from git tracking?

**Comment by chiazo** [comment]
@deeptivaidy @EduardoSantos7 @garciajess I removed the extra files!

**Review by garciajess — APPROVED** [review]
LGTM :)

**Review by deeptivaidy — APPROVED** [review]
LGTM too!

**Pull request merged**
