### PR TITLE
Create new task form

### PR DESCRIPTION
**Pull request by garciajess**
Form includes fields for title, date, and level of importance.

### CODE REVIEW

**Comment by EduardoSantos7** [comment]
Hi Jess, just a quick check before the review, we should be in reviewers instead oof Assignees. Probably an image of the website will be helpful too.

**Comment by garciajess** [comment]
@EduardoSantos7 Thanks for catching that! I switched you all to reviewers. 
newForm

**Review by EduardoSantos7 — APPROVED** [review]
Good Job! I like it! 👍  The background is cool. 💯 

I just wasn't to mention that there're style libraries like [bootstrap](https://getbootstrap.com/) or [materialize](https://materializecss.com/) that you can check. I think will be nice to use one of them on the website. You can check how I used it in my [portfolio](https://esantosdelgado1-sps-summer20.uc.r.appspot.com/) but you can find a lot of other better examples in Google. 

Great work!

Suggestion: You can use a Bootsrap card for the form.

Let me know if you have a doubt about how to use them.

**Review by deeptivaidy — COMMENTED** [review]
It looks like there are two `index.html` files in our directories, should we get rid of one of them? The one inside the webapp folder is empty.
Screen Shot 2020-07-04 at 1 10 23 PM

**Comment by deeptivaidy** [comment]
Also when I try to run the website from the eisenhower-matrix/eisenhower-matrix/ directory I only see a blank screen. Should index.html, style.css, and mountain.jpeg be in the webapp folder or does it matter?

**Comment by chiazo** [comment]
I love love love the background! I'm going to add some css styling Eduardo mentioned, especially to style the login & logout buttons I'm adding :)

**Pull request merged**
