### PR TITLE
Implements delete comments in backend

### PR DESCRIPTION
**Pull request by chiazo**
This code POSTS the id of a deleted comment to the backend so it can be deleted from DataStore! It does so by adding an invisible form to the HTML that can be called from the javascript file.

### CODE REVIEW

**Comment by deeptivaidy** [comment]
When I try to submit using the "Select one.." option, I get a backend java error since the option isn't within 1-4. Is there some way we can limit the form submission if this option is chosen, from the front-end or back-end?

**Comment by chiazo** [comment]
@deeptivaidy Oh wow ok, hopefully anyone pushing soon can just remove that option from the form!

**Comment by deeptivaidy** [comment]
Okay cool! Should I just push it to this branch so that we can add it to the PR?

**Review by deeptivaidy — APPROVED** [review]
Added the change, LGTM!

**Pull request merged**
